<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMFroYoM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMFroYoM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMFroYoM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMFroYoM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMFroYoM\App_KernelDevDebugContainer([
    'container.build_hash' => 'MFroYoM',
    'container.build_id' => '9f1523b9',
    'container.build_time' => 1709889414,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMFroYoM');
