<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCRuVERa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCRuVERa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCRuVERa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCRuVERa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCRuVERa\App_KernelDevDebugContainer([
    'container.build_hash' => 'CRuVERa',
    'container.build_id' => '265b0b8f',
    'container.build_time' => 1709897597,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCRuVERa');
